name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build-macos-x86_64:
    runs-on: macos-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v1
      with:
        repository: fantix/edgedb-pkg
        ref: gsed
        path: edgedb-cli/edgedb-pkg

    - uses: actions/cache@v2
      id: sdk1010cache
      with:
        path: ~/.cache/MacOSX10.10.sdk/
        key: MacOSX10.10.sdk

    - name: Install Xcode
      if: steps.sdk1010cache.outputs.cache-hit != 'true'
      run: |
        xcversion install 6.4

    - name: Cache 10.10 SDK
      if: steps.sdk1010cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.cache
        cp -a \
          /Applications/Xcode-6.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/ \
          ~/.cache/MacOSX10.10.sdk/

    - name: Select macOS SDK
      run: |
        sudo cp -a \
          ~/.cache/MacOSX10.10.sdk/ \
          /Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/
        sudo xcode-select -s /Library/Developer/CommandLineTools

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build
      env:
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "macos"
        PKG_PLATFORM_VERSION: "x86_64"
        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/
        PACKAGE: edgedbpkg.edgedbcli:EdgeDBCLI

        BUILD_GENERIC: true

      run: |
        xcrun --show-sdk-path
        edgedb-pkg/integration/macos/build.sh

    - uses: actions/upload-artifact@v1
      with:
        name: builds-macos-x86_64
        path: artifacts/macos-x86_64
